#ifndef CONSTANTES_H
#define CONSTANTES_H

#define MAXNOMEPESSOA 100
#define MAXNOMEDISCIPLINA 300
#define MAXCPF 11
#define MAXALUNOS 3
#define MAXPROFESSORES 3
#define MAXDISCIPLINAS 3
#define MAXALUNOSDISCIPLINAS 50

#endif